#!/bin/sh
TMP=/tmp/bkrcmd

echo 'beep off'  > $TMP
echo 'sendpv on' >> $TMP
echo 'resign 32599' >> $TMP
echo 'connect wdoor.c.u-tokyo.ac.jp 4081 TestWhale4 floodgate-900-0,mytrip 1' >> $TMP
#echo 'connect localhost 4081 TestWhale4 test-900-0' >> $TMP

while :
do
    mpiexec -host localhost -n 1 gmx -tf -y0 -h0 -a -m0 : \
            -host localhost -n 2 gmx         -h3 -a -s1 -4 \
            < $TMP
    sleep 10
done
