slave3.o: slave3.cpp stdinc.h if_bonanza.h bonanza6/shogi.h \
 bonanza6/bitop.h bonanza6/param.h bonanza6/inline.h comm3.h splane.h \
 perfsl.h sbody3.h
putils.o: putils.cpp stdinc.h if_bonanza.h bonanza6/shogi.h \
 bonanza6/bitop.h bonanza6/param.h bonanza6/inline.h
invokempi.o: invokempi.cpp stdinc.h if_bonanza.h bonanza6/shogi.h \
 bonanza6/bitop.h bonanza6/param.h bonanza6/inline.h
master3.o: master3.cpp stdinc.h if_bonanza.h bonanza6/shogi.h \
 bonanza6/bitop.h bonanza6/param.h bonanza6/inline.h comm3.h plane.h \
 entsort.h initact.h time.h
u2g.o: u2g.c
