perl majority_server.pl --client_port=4082 \
                        --client_num=1 \
                        --csa_host=localhost \
                        --csa_port=4081 \
                        --csa_id=bonachan \
                        --csa_pw=test-99999-99999-B \
                        --sec_limit=0 \
                        --sec_limit_up=10 \
                        --time_response=0.15 \
                        --time_stable_min=11.0 \
                        --sec_spent_b=0 \
                        --sec_spent_w=0 \
                        --noaudio \
                        --final_as_confident
